### ISSUE TITLE
Where are CT's First Congressional elections?

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#10]
Lincoln Mullen [4:25 PM] 
In this file, `ct.congress.1790` is listed as the second Congress. Did you figure that out from the date? Based on the results, I think it is the first Congress.

[4:26] 
Because the date would make sense for the second Congress, but maybe CT was late about electing people.

Jordan Bratt [4:31 PM] 
The results I am looking at don't match either the first or the second congress (according to Martis). (edited)

Lincoln Mullen [4:32 PM] 
I was basing that thought on Roger Sherman only being elected to the First Congress.

[4:32] 
But he was the only one I looked at.

Jordan Bratt [4:33 PM] 
Yeah. He is the only one from `ct.congress.1790` listed in the first congress. Yet, only Hillhouse, Sturges, and Trumbull match in the second congress.

Lincoln Mullen [4:34 PM] 
Huh.

[4:35] 
It’s odd, because `ct.congress.1790` is the earliest election for Connecticut, which also make me think it was first congress.

[4:35] 
I will open an issue until we get to the bottom of this.

**Comment by lmullen** [comment]
@jfbratt I am pretty sure that `ct.congress.1790` is the election to the First Congress. I've marked it as such in the `maps-to-elections` table. Could you please go through all the CT Congressional elections in that table and check that they are correctly associated with the NNV elections?

**Comment by lmullen** [comment]
BTW, @jfbratt, there was a 1790 special election which replaced one elected candidate who refused to serve, which accounts for 4 out of the 5 people who are listed in the CongBio as serving in the first Congress. My guess is that the fifth didn't get elected initially but then replaced someone else, though we will have to figure that out.

**Comment by jfbratt** [comment]
`ct.congress.1818` for the 16th Congress lists a "Seth A. Foot" as being elected. There is no such individual in the Congressional Biography but there is a "Samuel Foot" elected to the 16th Congress from CT. 

UPDATE: Changed Seth A. Foot's candidate ID to Samuel (same person) in the XML file.

**Comment by jfbratt** [comment]
@lmullen `ct.congress.1790` matches both the 1st and 2nd congress fairly closely but I am thinking it is for the 2nd Congress. First, it lists "James Hillhouse" as elected and his Congressional Bio only has him elected to the 2nd, 3rd, and 4th Congresses before becoming a Senator. Second, the election year is during the 1st Congress (1789-1791) and the Congressional Bio lists those reps who served in the 1st Congress from Connecticut as serving from March 1789 - March 1791. However, if it is the election for 2nd Congress, I can't account for "Amasa Learned" who is listed in Martis and Congressional Bio has as "elected as a Pro-Administration candidate to the Second and Third Congresses (March 4, 1791-March 3, 1795)." 

If I use `ct.congress.1790` as the 1st Congress, I can't account for both James Hillhouse (listed in the XML file but not in Martis or in Congressional Bio for the 1st Congress) or Benjamin Huntington (listed in Martis and as "elected as a Pro-Administration candidate to the First Congress" in the Congressional Bio).

**Comment by jfbratt** [comment]
Additionally, `ct.congress.1796` should match up with the 5th Congress (`ct.congress.1798` matches the 6th Congress and `ct.congress.1794` matches the 4th Congress) but it is fairly messy. In total, 5 out of 7 from the XML file match with Martis and the Congressional Bio (Coit, Dana, Goodrich, Griswold, and Smith). That leaves Zephaniah Swift and Uriah Tracy from the XML file that unaccounted for (though I think Tracy was elected as a Senator after the election for the House). Martis and the Congressional Bio have 4 individuals who aren't in the XML. 1 of them is accounted for in a special election in NNV (ct.special.congress.1797). I can't reconcile the other 3 (Davenport, Allen, and Brace) with NNV.

**Comment by lmullen** [comment]
@jfbratt If 1794 is the 4th and 1798 is the 6th, then 1796 must be the 5th. You can put it that way in the dataset. We will sort out all the messy details of who got elected when we write the text for that map. But I'll keep in mind that you've already figured out the problems here.

**Comment by lmullen** [comment]
Mystery solved. Here is part of the reply from Phil.

> All of the Connecticut newspapers I checked for the 1788 congressional election in that state, only listed the names of the individuals chosen, none gave any votes.  That election was held on December 22, 1788. 

So `ct.congress.1790` is for the Second Congress, as we thought. The First Congress information is not in NNV at all. I will fix CT01 and CT02 in the data files and remove CT 01 from the website. When Phil sends me the list of candidates for CT 01, we can include a table of the winners and leave it at that.
