### ISSUE TITLE
Correct winners in data and map text on site for RI07 and RI08

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#108]
From Rosie:

> I am confused about what is going on in RI in Congress 7 and 8. In Congress #7 (1800), the text says RI lost one seat after reapportionment. Then in the 8th Congress (1802), it says RI received one more seat after reapportionment.  Something is incorrect here. The results of the census would not have been available by the 7th Congress in 1800. I wonder whether, if for some strange reason, RI elected only one Congressman in 1800? In any case, by 1802, RI had 2 members again. This was not the result of reapportionment, in either case. 

And the resolution:

> Mystery solved.  II did a bit more digging. Joseph Stanton and Thomas Tillinghast were both elected from RI for the 7th Congress. For the 8th Congress, Joseph Stanton and Nehemiah Knight were elected. 
>
> So we need to remove the reference to reapportionment in the 7th and 8th Congresses. And note that Stanton was elected in the 7th.

**Comment by jfbratt** [comment]
Removed the reapportionment text, marked Joseph Stanton Jr. as elected and added the 2nd ballot to the NNV Data second on RI07.
