### ISSUE TITLE
nn instead of NA?

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#124]
For `meae.congressional.congress19.oh.county` and `ohs_greene` county in the `congressional-counties-parties.csv` file, one of the values was `nn`. I presume this was supposed to be `NA`, @jfbratt? I've corrected it in [this commit](https://github.com/mapping-elections/elections-data/commit/57a5ea8af6294e8136bf59809b6135921dd01b4e). If that was correct, you can close this issue.

**Comment by jfbratt** [comment]
Typo on my part. Thanks for catching it.
