### ISSUE TITLE
MA 3rd Congress election process

### ISSUE THREAD

**Issue by jfbratt** [mapping-elections/elections-data#16]
The election process for the 3rd Congress in Massachusetts is "unique". Here is the explanatory text from NNV about the process:
"The Massachusetts law provided for a complex method of voting. The voters of Districts One and Two each could vote for four candidates, but the votes had to be distributed as follows: one vote for a candidate from each of the three counties in the district and one additional vote for any candidate from any part of the district. In the Third District each voter had two votes; one had to be cast for a candidate from Barnstable, Dukes and Nantucket counties and the other for a candidate from Bristol and Plymouth. In addition all voters in the above three districts cast one additional vote for any candidate from anywhere in the three districts, listed in the returns as at-large. Voters of the Fourth District had three votes, one for a candidate from York, another from Cumberland and the other from any of the remaining counties of this district." Dubin, Michael J. United States Congressional Elections, 1788-1997: The Official Results of the Elections of the 1st through 105th Congresses. Jefferson, NC: McFarland and Company, 1998. 9.

**Comment by lmullen** [comment]
I was going to say something rather uncomplimentary about MA03, but suffice it to say that this issue is now closed.
