### ISSUE TITLE
Correct Hasbrouck's IDs

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#19]
Pick one Hasbrouck to keep his NNV ID.
The other Hasbrouck cousin gets a brand new NNV ID in all the places where he appears in the dataset. This needs to be corrected in the table of votes, in the table of people, and in the table that connects to the Congressional bio.

The ID which is erroneously shared by two people is `HA0085`.

**Comment by jfbratt** [comment]
I gave the currently assigned NNV ID of `HA0085` to Abraham Joseph Hasbrouck and assigned Abraham Bruyn Hasbrouck the NNV ID of `HA0234`. I added this new NNV ID to `elections.csv`, `congressional-counties.csv`, and corrected it in the Congressional Bio CSV.
