### ISSUE TITLE
Duplicate candidate_ids in congbio_candidates 

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#24]
@jfbratt There are 4 duplicate values for `candidate_id` in `congbio_candidates.csv`. See the image of a table below. Those are probably people who need to be disambiguated. Or it could be duplicate listings in Congbio for at least one of them. Could you please take a look and see what's going on here?

<img width="669" alt="screenshot 2017-10-11 10 55 13" src="https://user-images.githubusercontent.com/183672/31448781-44531a5c-ae73-11e7-9c38-2943451adcbb.png">

**Comment by lmullen** [comment]
Note that I've unified the `candidates.csv` and the `congbio_candidates.csv` into just the single candidates table that we need. I did that in d38f41d9960da971512dcf1360b13314442ab4f1. So you can look for these duplicates in `candidates.csv` now.

**Comment by jfbratt** [comment]
MJ0540: There are two Joseph MacDowells that serve in Congress from NC's 1st district. Joseph "Pleasant Gardens" MacDowell serves in the 3rd Congress and Joseph "Quaker Meadows" MacDowell runs and loses a bid for the 4th but is elected to the 5th Congress. The two are cousins. There are two elections (failed bids for the 1st and 2nd Congresses) that contain a "Joseph MacDowell" but Congressional Bio does not provide additional information to differentiate which one ran in those elections. (NNV candidate page: https://elections.lib.tufts.edu/catalog/MJ0540)

**Comment by jfbratt** [comment]
"Pleasant Gardens" MacDowell: MJ0540
"Quaker Meadows" MacDowell: ZZ0007
