### ISSUE TITLE
Oddities in congbio_elected.csv

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#25]
@jfbratt There are a few oddities in the `congbio_elected.csv` table. Could you please look into these? Note that the table is sorted Representatives first, Senators second, then ordered by Congress and State. Here are some examples:

1st Congress, CT: Districts should be with representatives, not senators. Duplicate 1 district. MEAE_IDs from different states. Duplicate senators.

<img width="845" alt="cong1-ct" src="https://user-images.githubusercontent.com/183672/31465254-6722b028-aea1-11e7-9287-4919422c82e7.png">

2nd Congress, CT: Same basic problems.

<img width="840" alt="cong2-ct" src="https://user-images.githubusercontent.com/183672/31465307-976fdb48-aea1-11e7-8da6-c01856f70171.png">

1st Congress, MA: Mostly correct, but 4th district should presumably be labeled for the representative without a district.

<img width="836" alt="cong1-ma" src="https://user-images.githubusercontent.com/183672/31465326-aec0071e-aea1-11e7-95dd-80722d6d9977.png">

1st Congress, NY: This one looks completely correct.

<img width="827" alt="cong1-ny" src="https://user-images.githubusercontent.com/183672/31465385-d301b8d4-aea1-11e7-8090-27b259fd5524.png">

**Comment by lmullen** [comment]
Note that we don't really need the meae_id here. So if it is easier to delete that, that's fine.

**Comment by jfbratt** [comment]
Interesting. CT shouldn't have any districts listed as it holds at-large elections. I will investigate further.

**Comment by jfbratt** [comment]
Fixed in commit 815ec0c
