### ISSUE TITLE
Correction to Maryland from Lampi

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#30]
- [x] 1798 – 7th District: Person elected is not noted.
- [x] 1801 – 3rd District: Person elected is not noted.
- [x] 1803 – 3rd District: Person elected is not noted.
- [x] 1804 -  4th District: In the Election Summary the votes should be Eli Williams 14, and Roger Nelson 1626. They are listed as Eli Williams 1626 and Roger Nelson 14.   
- [x] 1806 – 2nd District: In the Election Summary the votes should be Archibald Van Horn 1899 and Leonard Covington  1349, They are listed as Archibald Van Horn 1349 and Leonard Covington 1899.

**Comment by jfbratt** [comment]
Fixed in commit 8a24f47
