### ISSUE TITLE
Check PA 04 from Zagarri

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#37]
In the chart for Pennsylvania 4th Congress, MacClay rather than Hanna was checked as the winner. But Hanna got more votes: 1988 to 1985.

**Comment by jfbratt** [comment]
Both NNV and Congressional Bio note that MacClay was elected to the 4th Congress. Additionally, the Congressional Bio states that Hanna was first elected to Congress in the 5th Congress. I am not sure how to reconcile that with the raw vote count.

**Comment by lmullen** [comment]
Phil says that the NNV transcribers made a mistake and counted the military encampments separately, though they were counted in the county where they were encamped. In the MacClay/Hanna election in district 6, they were encamped in Dauphin county as we suspected.

Here is a file he sent with the correct totals for that district.

[Pennsylvania 1794 District # 6 - Sent to Lincoln Mullen.xlsx](https://github.com/mapping-elections/elections-data/files/1529299/Pennsylvania.1794.District.6.-.Sent.to.Lincoln.Mullen.xlsx)

Can you (1) correct district 6 and (2) make the same kind of corrections to the other military encampments?

**Comment by lmullen** [comment]
[Pennsylvania.1794.election.-.sent.to.Lincoln.Mullen.xlsx](https://github.com/mapping-elections/elections-data/files/1531814/Pennsylvania.1794.election.-.sent.to.Lincoln.Mullen.xlsx)

**Comment by lmullen** [comment]
Here is some additional information from Phil.

> Am sending you another attachment, which hopefully will help with your question. It does appear that some of the returns initially reported in the newspapers did not include the army[militia] votes. Because the army/militia votes had to be included in the counties from where those individuals lived, those votes were not often included in first election results.  Some counties waited until the militia votes came in, others just noted that their returns did not included them. The attachment makes note of those counties. There were several districts in which candidates were unopposed and no returns were reported, so am not sure if there were any militia/army votes from those districts.

> Some of the militia/army votes as reported in newspapers were unofficial and others came in too late and not counted. Those returns counted and accepted are on microfilm, which was sent to Tufts and entered by people there, so I never saw any of this information. Most of the data I used was taken from newspapers and some photocopies of Original Election Certificates. I do have the microfilm here with those returns and can check if you have any more questions.

[Pennyslvania 1794 Congress - Army Votes and notes.xlsx](https://github.com/mapping-elections/elections-data/files/1532237/Pennyslvania.1794.Congress.-.Army.Votes.and.notes.xlsx)

@jfbratt Please focus primarily on the MacClay/Hanna election, then we can use this new information from Phil to check the rest of the elections. After MacClay and Hanna, the rest of the issues are more important.

**Comment by jfbratt** [comment]
The only district returns that were affected by military counts (in a double counting manner) was district 6. All other district returns incorporated the military units as towns within counties and the voting return counts matched the document sent by Phil.

**Comment by lmullen** [comment]
Okay, good to know that it was not as widespread a problem as I thought.
