### ISSUE TITLE
SC 1794 from Lampi

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#39]
> District # 2 – This is really a special election for District # 5, to replace Alexander Gillon, who was elected in February 1793. This special election was held in November 1794, after the regular elections of October, in which Robert G. Harper was chosen. By this election he was then able to represent this district and finish the term of Alexander Gillon.

@jfbratt Do we have the right election listed for district 2?

**Comment by jfbratt** [comment]
Already fixed in the data tables. Removed district 2 election from SC04.Rmd file and pushed to `site` repo.
