### ISSUE TITLE
NC 1793 from Lampi

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#40]
> North Carolina
> 1793
> District # 1 – Joseph McDowell [R] is listed twice.  He was apparently unopposed.

@jfbratt Do we have a duplicated row or rows?

Same problem in 1796 election.

> District # 1 – Joseph McDowell [R] is again listed twice. His opponent was James Holland [R], the incumbent.

**Comment by lmullen** [comment]
And can you also look into this part?

> District # 9 – There are no returns listed for this district. Thomas Blount [R] was elected. He had > two opponents; John B. Ashe [R] and John Leigh [F].

**Comment by jfbratt** [comment]
Duplicate Joseph MacDowells for NC in our `candidates.csv` table. Both sharing the same NNV id. Fixed in commit 6c90556.

**Comment by jfbratt** [comment]
District 9: No raw vote totals and no one was marked as elected. All three candidates did not meet the threshold of 5% to be listed in the table.
