### ISSUE TITLE
Duplicate listings in MA 1794 and 1797 from Lampi

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#41]
Massachusetts 1794: For District # 6 John Reed is listed twice. Also note that the correct spelling of the last name is Reed. His name is given as John Reed in the Biographical Directory of Congress.
 
Massachusetts 1797: For District # 6 Again, John Reed is listed twice.

**Comment by jfbratt** [comment]
Joining issue for John Reed/Read in our candidates.csv table. Both shared the same NNV id. Fixed in commit 6c90556.
