### ISSUE TITLE
Foster v West

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#43]
@jfbratt This somewhat cryptic issue needs looking into. We can talk about it tomorrow.

Fix Foster v West.

Abiel Foster didn't win; Benjamin West did. Explain the discepancy in the text.

**Comment by jfbratt** [comment]
This is for NH 1st Congress. We created that map page before we solidified our election definition. Benjamin West was elected but declined to serve. Abiel Foster was elected in a special election (https://elections.lib.tufts.edu/catalog/tufts:nh.uscongress.special.1789). We need to update our `congressional-candidates-total.csv`.
