### ISSUE TITLE
NY 3rd, 4th, 5th Congress District numbering

### ISSUE THREAD

**Issue by jfbratt** [mapping-elections/elections-data#48]
Districts 7 & 8 and 1 & 2 swap numbering from the 3rd to the 4th Congress and then back again from the 4th to the 5th Congress. Follow the NNV data through and write up question for Phil.

**Comment by lmullen** [comment]
Here is Phil's response.

> For the 4th Congress [1794], District # 1 is Kings, Queens & Suffolk; # 2 is New York City;  # 7 is Albany, and District # 8 is Clinton & Rensselaer. These should also apply to 1796, which are listed correctly. When I first starting putting New York data together, information from Alfred Young’s book was used and he had lined up New York districts differently. At some point, based on other information, I corrected some of the district numbers, but apparently not all.   

> New York was among several states that conducted State Census, in the middle of a decade, 1795, 1805, etc., and the districts in 1798 actually changed, based on their state census. So when you get to that year, the districts will be different.

Does that make sense to you? I.e., do the changes that should be made to make the districts line up make sense?
