### ISSUE TITLE
Check congbio-winners.csv for MA03

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#58]
I think there are supposed to be 14 winners but there are 13. The difference might be Theodore Sedgwick.

**Comment by lmullen** [comment]
This does not have to be done before release, BTW.

**Comment by jfbratt** [comment]
I am assuming that you already took care of this. There are 14 candidates labeled as elected (including Theodore Sedgwick). I checked each of the NNV links against our table (100% accurate) and clicked through each of the links to the Congressional Bio and they are accurate.
