### ISSUE TITLE
Missing County Returns: 6th Congress, SC, District 2 (Beaufort District)

### ISSUE THREAD

**Issue by DanielKim1** [mapping-elections/elections-data#62]
The counties in District 2 are not represented in congress06-SC-county-returns.csv
https://elections.lib.tufts.edu/catalog/tufts:sc.uscongress.beaufort.1798

**Comment by jfbratt** [comment]
This is another parish vs. district vs. county issue. There are returns for the District of Beaufort and within that there are returns for Prince William Parish. For this congress, we have mapped largely only counties (the majority of the returns are from counties) and a handful of parishes. So the question is should we map this district return or the parish return? Additionally, there is no corresponding Beaufort county like many of the districts have. Beaufort county is formed in 1868 when the district system in SC is abolished (thank goodness).

**Comment by jfbratt** [comment]
Listed returns for Beaufort district, Orange County, and Saxe-Gotha Parish (listed as Lexington County on map - no geography for Saxe-Gotha Parish in AHCB).
