### ISSUE TITLE
CT05/CT06 John Allen election

### ISSUE THREAD

**Issue by jfbratt** [mapping-elections/elections-data#66]
In NNV, John Allen is a candidate in CT05 (not elected) and in CT06 (elected). Congressional Bio and history.house.gov list John Allen as being elected in CT05 and declining renomination in CT06. Additionally, history.house.gov quotes John Allen's support of the Sedition Act of 1798 (which was during the 5th congress).

https://elections.lib.tufts.edu/catalog/tufts:ct.congress.1796
https://elections.lib.tufts.edu/catalog/tufts:ct.congress.1798

**Comment by lmullen** [comment]
Resolved in Slack and adding text to that page to explain.
