### ISSUE TITLE
Missing County Returns: 8th Congress, SC, All Districts

### ISSUE THREAD

**Issue by DanielKim1** [mapping-elections/elections-data#67]
congress08-SC-county-returns.csv was completely empty.
District 1 (Charleston District) has been added in.

https://elections.lib.tufts.edu/catalog/tufts:sc.uscongress.charleston.1803
https://elections.lib.tufts.edu/catalog/tufts:sc.uscongress.edgefield.1803
https://elections.lib.tufts.edu/catalog/tufts:sc.uscongress.georgetown.1803
https://elections.lib.tufts.edu/catalog/tufts:sc.uscongress.orangeburg.1803
https://elections.lib.tufts.edu/catalog/tufts:sc.uscongress.sumter.1803
https://elections.lib.tufts.edu/catalog/tufts:sc.uscongress.abbeville.1803
https://elections.lib.tufts.edu/catalog/tufts:sc.uscongress.chester.1803
https://elections.lib.tufts.edu/catalog/tufts:sc.uscongress.pendleton.1803

**Comment by jfbratt** [comment]
Corrected in commit [43e0215](https://github.com/mapping-elections/elections-data/commit/43e02159601d5e3b9be5a48db922b0aa5f272e03)
