### ISSUE TITLE
2 Elections Associated for DE, 9th Congress

### ISSUE THREAD

**Issue by DanielKim1** [mapping-elections/elections-data#68]
congress09-DE-candidate-results.csv and congress09-DE-county-returns.csv contain both the data from the 1804 election and the 1805 special election.

https://elections.lib.tufts.edu/catalog/tufts:de.uscongress.1804
https://elections.lib.tufts.edu/catalog/tufts:de.uscongress.1805

**Comment by jfbratt** [comment]
Fixed in commit [f02eb1f ](https://github.com/mapping-elections/elections-data/commit/328095d3237ed2525e78d7b4eead34a69a9bcfc1)
