### ISSUE TITLE
Elections listed for SC04

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/elections-data#81]
@jfbratt Could you please check the maps to elections table for SC04? The elections listed seem incomplete, and they are also inconsistent with what is listed in the YAML header for that page. @DanielKim1 will need this to check the back filling.

**Comment by jfbratt** [comment]
NNV contains 3 elections for SC04. The 1st and 5th district are mapped correctly and the other election in NNV is a special election for district 2. The map reflects the data that is present in NNV and what is listed in the YAML. 

We could map the special election for the 2nd district and make a note of that in the body text.

**Comment by lmullen** [comment]
The problem is that the data is missing from NNV. We filled in the data where it was known from CongBio and other sources.
